"""Annual tax export — one-shot script the operator runs before
filing each year.

Phase 4 Part 2.1.

Usage::

    uv run python -m scripts.generate_annual_export --year 2026

Writes ``data/exports/annual/<year>/`` with:

- ``full_trade_log.csv``         — every closed trade for the year
- ``yearly_summary.json``        — aggregated stats
- ``form_8949_format.csv``       — IRS Form 8949 column layout
- ``kalshi_reconciliation.json`` — line-item totals to compare
                                    against Kalshi's 1099-B
- ``README.md``                  — explains each file + caveats

Reads from the existing daemon database (no separate copy). Idempotent —
re-running overwrites the four files in-place.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from trumpbot.config import load_config  # noqa: E402
from trumpbot.db.connection import Database  # noqa: E402
from trumpbot.exports.tax_exports import TaxExporter, write_export  # noqa: E402
from trumpbot.platform_paths import current_platform_paths, resolve_path  # noqa: E402

_README_TEMPLATE = """# Annual tax export — {year}

Generated by ``scripts/generate_annual_export.py``. Source data lives in
the daemon database (``trumpbot.db``); these files are exports for
filing-time use.

## Files in this directory

### ``full_trade_log.csv``

Every closed trade for tax year {year}. Sorted ascending by acquired
date. Columns:

- ``trade_id``                 — internal id; cross-reference with
                                 ``/why <trade_id>`` in Telegram
- ``ticker``                   — Kalshi ticker
- ``market_description``       — ticker plus market title for
                                 self-describing rows
- ``acquired_date``            — YYYY-MM-DD when the position opened
- ``disposed_date``            — YYYY-MM-DD when the position closed
- ``holding_period_days``      — calendar days held
- ``quantity``                 — contract count
- ``acquisition_cost_usd``     — entry price x qty + entry fees
- ``disposal_proceeds_usd``    — exit / settlement value, less exit fees
- ``realized_gain_loss_usd``   — proceeds minus cost
- ``status``                   — terminal trade status
- ``resolution_outcome``       — plain-English status
- ``notes``                    — first 400 chars of the engine's
                                 reasoning text

Suitable for import into spreadsheets or accountant software.

### ``yearly_summary.json``

Top-level aggregated stats — totals, win/loss counts, largest
gain/loss with the market that produced them, average holding period,
per-ticker breakdown. Matches the ``/tax_summary`` Telegram output.

### ``form_8949_format.csv``

IRS Form 8949 column layout. Columns named exactly per the official
form spec:

- Description of property
- Date acquired
- Date sold or disposed of
- Proceeds (sales price)
- Cost or other basis
- Adjustment, if any   (left blank — situation-specific)
- Code, if any         (left blank — situation-specific)
- Gain or (loss)

Hand to your accountant or paste into TurboTax / FreeTaxUSA
section-by-section.

### ``kalshi_reconciliation.json``

Per-trade totals in the shape Kalshi's 1099-B uses, suitable for
line-item comparison once Kalshi issues the form (typically February
of the following year). Use ``scripts/import_kalshi_1099.py`` once
the form arrives.

## Caveats

- All trades in this export are short-term capital gains. Kalshi
  contracts resolve in days-to-weeks, well under the 1-year long-term
  threshold.
- ``Adjustment`` and ``Code`` on Form 8949 are left blank. If the
  operator had wash sales or basis-not-reported-to-IRS situations,
  the accountant will fill those in.
- Exit fees on settlement are 0 (Kalshi's fee formula returns 0 at
  resolution prices). Stop-loss exits do incur fees and they are
  netted into ``disposal_proceeds_usd``.
- Money fields are exact integer cents internally; the dollar
  formatting here uses two decimal places with no float drift.

## How to use

1. Run this script for the year you're filing:
   ``uv run python -m scripts.generate_annual_export --year {year}``
2. Review ``yearly_summary.json`` for totals.
3. Hand ``full_trade_log.csv`` and ``form_8949_format.csv`` to your
   accountant.
4. When Kalshi issues the 1099-B, run
   ``uv run python -m scripts.import_kalshi_1099 --file <pdf> --year {year}``
   to compare the bot's records.
"""


def _amain(args: argparse.Namespace) -> int:
    cfg_path = Path(args.config).expanduser()
    if not cfg_path.is_file():
        print(f"config not found: {cfg_path}", file=sys.stderr)
        return 2
    cfg = load_config(cfg_path)
    paths = current_platform_paths()
    db_path = resolve_path(cfg.database.path, paths.database_path)
    db = Database(db_path)
    db.connect()
    exporter = TaxExporter(db)

    out_dir = (
        Path(args.out_dir).expanduser()
        if args.out_dir
        else db_path.parent / "exports" / "annual" / str(args.year)
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"Writing annual export for {args.year} to {out_dir}")

    full_log = exporter.export_trade_log(args.year, format="csv")
    write_export(out_dir / "full_trade_log.csv", full_log)
    print(f"  ✓ full_trade_log.csv ({len(full_log.splitlines()) - 1} trades)")

    summary = exporter.export_yearly_summary(args.year)
    write_export(
        out_dir / "yearly_summary.json",
        json.dumps(summary.as_dict(), indent=2, sort_keys=True),
    )
    print(f"  ✓ yearly_summary.json (net P&L: {summary.net_pnl_cents}c)")

    form_8949 = exporter.export_form_8949_format(args.year)
    write_export(out_dir / "form_8949_format.csv", form_8949)
    print(f"  ✓ form_8949_format.csv ({len(form_8949.splitlines()) - 1} rows)")

    recon = exporter.export_kalshi_reconciliation(args.year)
    write_export(
        out_dir / "kalshi_reconciliation.json",
        json.dumps(recon, indent=2, sort_keys=True),
    )
    print(f"  ✓ kalshi_reconciliation.json ({len(recon['line_items'])} line items)")

    write_export(out_dir / "README.md", _README_TEMPLATE.format(year=args.year))
    print("  ✓ README.md")

    db.close()
    print("\nDone. Hand the CSVs to your accountant or import into TurboTax.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(prog="generate_annual_export")
    parser.add_argument(
        "--config",
        default=str(Path("~/.config/trumpbot/config.yaml").expanduser()),
    )
    parser.add_argument("--year", type=int, required=True, help="Tax year to export")
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Override the output directory (default: <db_dir>/exports/annual/<year>/)",
    )
    args = parser.parse_args()
    return _amain(args)


if __name__ == "__main__":
    sys.exit(main())
